config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :employees
  resources :students
  resources :images

  get "mail_page", to: "students#mail_page"
  get "/send_details", to: "students#send_details"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(search)
    if search
      where(["LOWER(name) LIKE ? OR LOWER(email) LIKE ?","%#{search}%", "%#{search}%"])
    else
      all
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }
  validates :phone_number, presence: true, length: { minimum: 10 }
  validates_format_of :phone_number, with: /\A(\d{10}|\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4})\z/, message: "Only positive number without spaces are allowed"
end

app/models/image.rb
class Image < ApplicationRecord
  validates :title, :img, :description, presence: true

  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }
  validates :phone_number, presence: true, length: { minimum: 10 }
  validates_format_of :phone_number, with: /\A(\d{10}|\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4})\z/, message: "only allows valid phone number"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }
  validates :phone_number, presence: true, length: { minimum: 10 }
  validates_format_of :phone_number, with: /\A(\d{10}|\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4})\z/, message: "only allows valid phone number"


  def self.to_csv
    attributes = %w{name email phone_number}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.order(:name).first(50).each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.search(params[:search])

    respond_to do |format|
      format.html
      
      format.pdf do
        pdf = EmployeesPdf.new(@employees)

        send_data pdf.render,
          filename: "Employees-#{Time.new.strftime("%d/%m/%Y-%H%M%S")}.pdf",
          type: "application/pdf", 
          isposition: "inline"
      end
    end
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)
    if @employee.save
      flash[:success] = "An employee is created successfully!"
      redirect_to @employee
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      flash[:success] = "Employee is updated successfully!"
      redirect_to @employee
    else
      render :new
    end
  end

  def destroy
    if @employee.destroy
      flash[:success] = "An employee is deleted successfully!"
      redirect_to employees_path
    end
  end

  private
    def employee_params
      params.require(:employee).permit(:name, :email, :phone_number)
    end

    def find_employee
      @employee = Employee.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all.order("created_at DESC")
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)

    if @image.save
      flash[:success] = "Image is uploaded successfully!"
      redirect_to @image
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @image.update(image_params)
      flash[:success] = "Image is updated successfully!"
      redirect_to @image
    else
      render :edit
    end
  end

  def destroy
    if @image.destroy
      flash[:success] = "An image is deleted successfully!"
      redirect_to images_path
    end
  end

  private
    def image_params
      params.require(:image).permit(:title, :img, :description)
    end

    def find_image
      @image = Image.find(params[:id])
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :edit, :update, :destroy]

  def index
     @students = Student.search(params[:search])
  end

  def show
  end
  
  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)

    if @student.save
      flash[:success] = "A student is created successfully!"
      redirect_to @student
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:success] = "Student is updated successfully!"
      redirect_to @student
    else
      render :edit
    end
  end

  def destroy
    if @student.destroy
      flash[:success] = "Student is deleted successfully!"
      redirect_to students_path
    end
  end

  def mail_page
    @student = Student.new
  end

  def send_details
    @students = Student.order(:name).first(50)
    @to = params[:email]

    StudentMailer.send_details(@students, @to).deliver_now
    flash[:success] = "Students details are sent successfully!"
    redirect_to root_path
  end

  private 
    def find_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :email, :phone_number)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.search(params[:search])
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "users-#{Time.now.strftime("%H%M%S")}.csv"}
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "An user is created successfully!"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "User is updated successfully!"
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "An user is deleted successfully!"
      redirect_to users_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :phone_number)
    end

    def find_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_form.html.erb
<% if @employee.errors.any? %>
   <h2><%= pluralize(@employee.errors.count, "error") %> prevented from saving! </h2>

  <ul class="danger">
    <% @employee.errors.full_messages.each do |msg| %>
      <li class="text-danger"> <%= msg %> </li>
    <% end %>
  </ul>
  
<% end %>


<%= form_for @employee do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter employee name", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: "Enter email", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number, placeholder: "Enter phone number", class: "form-control", required: true %>
  </div>

  <div>
    <%= form.submit "submit", class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class=" panel-head">
  <h1 class="text-center">Update employee information </h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', employees_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/employees/index.html.erb
<div class="panel-heading">
  
  <div class="row">
    <div class="col-md-6">
      <%= link_to "Create New", new_employee_path, class: "btn btn-default btn-primary col" %>
    </div>

    <div class="col-md-6">
      <%= form_for "", url: employees_path, role: "search", method: :get do %>
        <div class="row">
          <div class="col-md-9">
            <%= text_field_tag :search, @search_term, placeholder: "Search...", class: "form-control col-md-6 pull-right" %>
          </div>
          <%= submit_tag "search", class: "btn btn-default btn-primary col-md-2" %>
        </div>
      <% end %>
    </div>
  </div>

  <h2 class="text-center">All employees details</h2>
</div>

<div class="panel-body">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td> <%= employee.id %> </td>
          <td> <%= employee.name %> </td>
          <td> <%= employee.email %> </td>
          <td> <%= employee.phone_number %> </td>
          <td> <%= link_to "Show", employee, class: "btn btn-default btn-success" %> </td>
          <td> <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-default btn-primary" %> </td>
          <td> <%= link_to "Delete", employee, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-danger" %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/new.htm.erb
<div class="panel-heading">
  <h1 class="text-center">Create New student</h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', root_path %>
</div>

app/views/employees/new.html.erb
<div class="panel-heading">
  <h1 class="text-center">Create New Employee</h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', employees_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/employees/show.html.erb
<div class="panel-heading">
  <h1 class="text-center"> Employee-ID: E00<%= @employee.id %></h1>
</div>

<div class="panel-body">
  <div class="col-md-4 col-md-offset-4">
    <p><strong>Name:</strong> <span class="text-primary"><%= @employee.name %></span> </p>
    <p><strong>Email:</strong> <span class="text-primary"> <%= @employee.email %> </span></p>
    <p><strong>Phone Number:</strong> <span class="text-primary"> <%= @employee.phone_number %> </span> </p>
  </div>
</div>

<div class="panel-footer">
  <p class="text-warning text-center">employee ID: <%= @employee.id %> is created at: <span class="text-success"><%= @employee.created_at.strftime("%d/%m/%Y  %H:%M:%S") %>UTC</span> </p>
  <%= link_to 'Back', employees_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/home/index.html.erb
<div class="panel-heading">
  <h2 class="text-center text-warning">Welcome to User App</h2>
</div>

<div class="panel-body">
  <div class="thumbnail">
    <h3 class="text-center">Employees</h3>
    <div class="notice">
      <p class="caption">Download 50 employees details as pdf. <%= link_to "Download", employees_path(format: :pdf), class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>

    <div class="notice">
      <p class="caption">show all employees details. <%= link_to "Show", employees_path, class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>
  </div>

  <div class="thumbnail">
    <h3 class="text-center">Users</h3>
    <div class="notice">
      <p class="caption">Download 50 users details as csv. <%= link_to "Download", users_path(format: :csv), class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>

    <div class="notice">
      <p class="caption">show all users details. <%= link_to "Show", users_path, class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>
  </div>

  <div class="thumbnail">
    <h3 class="text-center">Students</h3>
    <div class="notice">
      <p class="caption">Send student details via mail. <%= link_to "Send Mail", mail_page_path, class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>

    <div class="notice">
      <p class="caption">show all students details. <%= link_to "Show", students_path, class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>
  </div>

  <div class="thumbnail">
    <h3 class="text-center">Image Gallery</h3>
    <div class="notice">
      <p class="caption">Go to gallery to view images. <%= link_to "Gallery", images_path, class: "btn btn-default btn-primary pull-right col-md-2" %> </p>
    </div>
  </div>
</div>

<div class="panel-footer">
  
</div>

app/views/images/_form.html.erb
<% if @image.errors.any? %>
   <h2><%= pluralize(@image.errors.count, "error") %> prevented from saving! </h2>

  <ul class="danger">
    <% @image.errors.full_messages.each do |msg| %>
      <li class="text-danger"> <%= msg %> </li>
    <% end %>
  </ul>
  
<% end %>
<%= form_for @image do |image|%>
  <div class="form-group">
    <%= image.label :title %>
    <%= image.text_field :title, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= image.label :img %>
    <%= image.file_field :img, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= image.label :description %>
    <%= image.text_area :description, class: "form-control form-control-lg" %>
  </div>

  <div class="submit">
    <%= image.submit "upload", class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/images/edit.html.erb
<div class="panel-heading">
  <h1 class="text-center">Update Uploaded image</h1>
</div>

<div class="panel-body">
  <%= render "form" %>
</div>
 
<div class="panel-footer">
  <%= link_to "Back", images_path, class: "btn btn-default btn-warning" %>
</div>

app/views/images/index.html.erb
<div class="panel-heading">
  <h1 class="text-center">Image Gallery</h1>
</div>

<div class="panel-body">
  <div class="row">
    <% if @images.count == 0 %>
      <p class="text-danger text-center">Gallery is empty, please upload!</p>
    <% end %>
    <% @images.each do |image| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= link_to (image_tag image.img.url(:medium)), image, class: "img-responsive" %>
          <p class="caption text-center">
            <%= link_to (image.title), image %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="panel-footer">
  <%= link_to "upload", new_image_path, class: "btn btn-default btn-primary" %>
</div>

app/views/images/new.html.erb
<div class="panel-heading">
  <h1 class="text-center">Upload Image</h1>
</div>

<div class="panel-body">
  <%= render "form" %>
</div>

<div class="panel-footer">
  <%= link_to "Back", images_path, class: "btn btn-default btn-warning" %>
</div>

app/views/images/show.html.erb
<div class="panel-heading">
  <h1 class="text-center">
    <%= @image.title %>
  </h1>
</div>

<div class="panel-body">
  <div class="thumbnail">
    <%= image_tag @image.img.url %>
    <p class="caption text-center"> <%= @image.description %> </p>
  </div>
</div>

<div class="panel-footer">
  <p class="text-success text-center">posted on: <%= @image.created_at.strftime("%d/%m/%Y %H:%M") %> GMT standards</p>

  <%= link_to "Back", images_path, class: "btn btn-default btn-warning" %>
  <%= link_to "Edit", edit_image_path, class: "btn btn-default btn-primary" %>
  <%= link_to "Delete", image_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class="text-center brand fixed-top">User App</h1>
      <span class=" home"> <%= link_to "Home", root_path %> </span>
    </header>
    <div class="container"> 
      <% flash.each do|name, msg| %>
        <%= content_tag :div, msg, class: "text-center text-success alert aler-info" %>
      <% end %>
      <div class="col-md-10 col-md-offset-1">
        <div class="row">
          <div class="panel panel-default">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <footer class="fixed-bottom">
      <p class="text-center">&copy; copyright ISO 20001</p>
    </footer>
  </body>
</html>

app/views/students/_form.html.erb
<% if @student.errors.any? %>
   <h2><%= pluralize(@student.errors.count, "error") %> prevented from saving! </h2>

  <ul class="danger">
    <% @student.errors.full_messages.each do |msg| %>
      <li class="text-danger"> <%= msg %> </li>
    <% end %>
  </ul>
  
<% end %>


<%= form_for @student do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter student name", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: "Enter email", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :mobile_no %>
    <%= form.text_field :phone_number, placeholder: "Enter mobile number", class: "form-control", required: true %>
  </div>

  <%= form.submit "submit", class: "btn btn-default btn-primary" %>
    
<% end %>

app/views/students/edit.html.erb
<div class=" panel-head">
  <h1 class="text-center">Update student information</h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', students_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/students/index.html.erb
<div class="panel-heading">
  
  <div class="row">
    <div class="col-md-6">
      <%= link_to "Create New", new_student_path, class: "btn btn-default btn-primary col" %>
    </div>

    <div class="col-md-6">
      <%= form_for "", url: students_path, role: "search", method: :get do %>
        <div class="row">
          <div class="col-md-9">
            <%= text_field_tag :search, @search_term, placeholder: "Search...", class: "form-control col-md-6 pull-right" %>
          </div>
          <%= submit_tag "search", class: "btn btn-default btn-primary col-md-2" %>
        </div>
      <% end %>
    </div>
  </div>

  <h2 class="text-center">All students details</h2>
</div>

<div class="panel-body">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td> <%= student.id %> </td>
          <td> <%= student.name %> </td>
          <td> <%= student.email %> </td>
          <td> <%= student.phone_number %> </td>
          <td> <%= link_to "Show", student, class: "btn btn-default btn-success" %> </td>
          <td> <%= link_to "Edit", edit_student_path(student), class: "btn btn-default btn-primary" %> </td>
          <td> <%= link_to "Delete", student, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-danger" %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/mail_page.html.erb
<div class="panel-heading">
  <h2 class="text-center">Send the student details...</h2>
</div>

<div class="panel-body">
  <%= form_for "", url: send_details_path, role: "mailing", method: :get do %>
    <div class="form-group">
      <%= email_field_tag :email, @mailing_term, placeholder: "Enter receiver email...", required: true, class: "form-control" %><br>
      <%= submit_tag "send", class: "btn btn-default btn-primary" %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<div class="panel-heading">
  <h1 class="text-center">Create New student</h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', students_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/students/show.html.erb
<div class="panel-heading">
  <h1 class="text-center"> Student-ID: S00<%= @student.id %></h1>
</div>

<div class="panel-body">
  <div class="col-md-4 col-md-offset-4">
    <p><strong>Name:</strong> <span class="text-primary"><%= @student.name %></span> </p>
    <p><strong>Email:</strong> <span class="text-primary"> <%= @student.email %> </span></p>
    <p><strong>Phone Number:</strong> <span class="text-primary"> <%= @student.phone_number %> </span> </p>
  </div>
</div>

<div class="panel-footer">
  <p class="text-warning text-center">student ID: <%= @student.id %> is created at: <span class="text-success"><%= @student.created_at.strftime("%d/%m/%Y  %H:%M:%S") %>UTC</span> </p>
  <%= link_to 'Back', students_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
   <h2><%= pluralize(@user.errors.count, "error") %> prevented from saving! </h2>

  <ul class="danger">
    <% @user.errors.full_messages.each do |msg| %>
      <li class="text-danger"> <%= msg %> </li>
    <% end %>
  </ul>
  
<% end %>


<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter user name", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: "Enter email", class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :mobile_no %>
    <%= form.text_field :phone_number, placeholder: "Enter mobile number", class: "form-control", required: true %>
  </div>

  <div>
    <%= form.submit "create", class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class=" panel-head">
  <h1>Edit User</h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', users_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/users/employees_pdf.html.erb
<div class="panel-head">
  <h1 class="text-center">All 50 employees details</h1>
</div>

<div class="panel-body">
  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Mobile Number</th>
      </tr>
    </thead>
    <tbody>
      <% @users.order(:name).first(50).each do |user| %>
        <tr>
          <td> <%= user.name %> </td>
          <td> <%= user.email %> </td>
          <td> <%= user.mobile_no %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="footer">
  <p class="text-center text-warning">Employees are listed according to name.</p>
  <p class="text-center">Time stamp: <%= Time.now %></p>
</div>

app/views/users/index.html.erb
<div class="panel-heading">
  
  <div class="row">
    <div class="col-md-6">
      <%= link_to "Create New", new_user_path, class: "btn btn-default btn-primary col" %>
    </div>

    <div class="col-md-6">
      <%= form_for "", url: users_path, role: "search", method: :get do %>
        <div class="row">
          <div class="col-md-9">
            <%= text_field_tag :search, @search_term, placeholder: "Search...", class: "form-control col-md-6 pull-right" %>
          </div>
          <%= submit_tag "search", class: "btn btn-default btn-primary col-md-2" %>
        </div>
      <% end %>
    </div>
  </div>

  <h2 class="text-center">All users details</h2>
</div>

<div class="panel-body">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td> <%= user.id %> </td>
          <td> <%= user.name %> </td>
          <td> <%= user.email %> </td>
          <td> <%= user.phone_number %> </td>
          <td> <%= link_to "Show", user, class: "btn btn-default btn-success" %> </td>
          <td> <%= link_to "Edit", edit_user_path(user), class: "btn btn-default btn-primary" %> </td>
          <td> <%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-danger" %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="panel-heading">
  <h1 class="text-center">Create New User</h1>
</div>

<div class="panel-body">
  <%= render 'form' %>
</div>

<div class="panel-footer">
  <%= link_to 'Back', users_path, class: "btn btn-default btn-warning"  %>
</div>

app/views/users/show_all.html.erb
<div class="panel-head">
  <%= link_to "Create User", new_user_path, class: "btn btn-default btn-primary" %>

  <h2>All Users details</h2>
</div>

<div class="panel-body">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Mobile Number</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td> <%= user.id %> </td>
          <td> <%= user.name %> </td>
          <td> <%= user.email %> </td>
          <td> <%= user.mobile_no %> </td>
          <td> <%= link_to "Show", users_path(user), class: "btn btn-default btn-primary" %> </td>
          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="panel-footer">
  <%= link_to "Back", root_path, class: "btn btn-default btn-primary " %>
</div>